version: '3.1'

services:
  db:
    image: postgres:12
    restart: always
    volumes:
        - "/var/docker/volumes/postgresql/data:/var/lib/postgresql/data:z"
    ports:
        - "5432:5432"
    environment:
      POSTGRES_PASSWORD: always99%
      PGDATA: /var/lib/postgresql/data/ 

volumes:
    mongodata: